export const SEED_LANGUAGES = [
  { code: 'vi', name: 'Vietnamese', native_name: 'Tiếng Việt' },
  { code: 'zh', name: 'Simplified Chinese', native_name: '简体中文' },
  { code: 'en', name: 'English', native_name: 'English' },
  { code: 'ja', name: 'Japanese', native_name: '日本語' },
  { code: 'ko', name: 'Korean', native_name: '한국어' },
  { code: 'fr', name: 'French', native_name: 'Français' },
  { code: 'de', name: 'German', native_name: 'Deutsch' },
  { code: 'es', name: 'Spanish', native_name: 'Español' },
  { code: 'ru', name: 'Russian', native_name: 'Русский' },
];

export const SEED_VOCABULARY = [
  // Chinese Vocabulary
  {
    word: '角色',
    language: 'zh',
    translation: 'nhân vật, vai trò',
    pinyin: 'juésè',
    part_of_speech: 'Danh từ (名词)',
    definition: 'Người hoặc đối tượng đại diện trong trò chơi, phim ảnh, kịch nghệ.',
    difficulty: 2,
    hsk_level: 4,
    source: 'screen_ocr',
    notes: 'Rất phổ biến trong game và phim ảnh (game character).',
    examples: [
      {
        sentence: '这个角色非常适合新手使用。',
        pinyin: 'Zhège juésè fēicháng shìhé xīnshǒu shǐyòng.',
        translation: 'Nhân vật này rất phù hợp cho người mới sử dụng.',
      },
      {
        sentence: '他在电影里扮演重要角色。',
        pinyin: 'Tā zài diànyǐng lǐ bànyǎn zhòngyào juésè.',
        translation: 'Anh ấy đóng một vai trò quan trọng trong bộ phim.',
      },
    ],
  },
  {
    word: '适合',
    language: 'zh',
    translation: 'phù hợp, thích hợp',
    pinyin: 'shìhé',
    part_of_speech: 'Động từ (动词)',
    definition: 'Đạt được yêu cầu, ăn khớp với hoàn cảnh hoặc điều kiện.',
    difficulty: 2,
    hsk_level: 3,
    source: 'dictionary',
    notes: 'Phân biệt với 合适 (Tính từ: thích hợp).',
    examples: [
      {
        sentence: '这本书很适合初学者。',
        pinyin: 'Zhè běn shū hěn shìhé chūxuézhě.',
        translation: 'Cuốn sách này rất phù hợp cho người mới học.',
      },
      {
        sentence: '这件衣服适合夏天穿。',
        pinyin: 'Zhè jiàn yīfu shìhé xiàtiān chuān.',
        translation: 'Bộ quần áo này thích hợp mặc vào mùa hè.',
      },
    ],
  },
  {
    word: '新手',
    language: 'zh',
    translation: 'người mới, lính mới (newbie)',
    pinyin: 'xīnshǒu',
    part_of_speech: 'Danh từ (名词)',
    definition: 'Người mới bắt đầu làm quen một lĩnh vực hoặc kỹ năng nào đó.',
    difficulty: 1,
    hsk_level: 3,
    source: 'screen_ocr',
    notes: 'Thường gặp: 新手教程 (hướng dẫn cho người mới).',
    examples: [
      {
        sentence: '我是个游戏新手，请多指教。',
        pinyin: 'Wǒ shì gè yóuxì xīnshǒu, qǐng duō zhǐjiào.',
        translation: 'Tôi là người mới chơi game, xin chỉ giáo nhiều hơn.',
      },
    ],
  },
  {
    word: '非常',
    language: 'zh',
    translation: 'rất, vô cùng, hết sức',
    pinyin: 'fēicháng',
    part_of_speech: 'Phó từ chỉ mức độ (副词)',
    definition: 'Mức độ cao hơn 很 (hěn).',
    difficulty: 1,
    hsk_level: 2,
    source: 'default',
    notes: 'Cấu trúc: 非常 + Tính từ / Động từ tâm lý.',
    examples: [
      {
        sentence: '我今天非常高兴。',
        pinyin: 'Wǒ jīntiān fēicháng gāoxìng.',
        translation: 'Hôm nay tôi vô cùng vui mừng.',
      },
    ],
  },
  {
    word: '简单',
    language: 'zh',
    translation: 'đơn giản, giản dị',
    pinyin: 'jiǎndān',
    part_of_speech: 'Tính từ (形容词)',
    definition: 'Không phức tạp, dễ hiểu, dễ làm.',
    difficulty: 1,
    hsk_level: 3,
    source: 'subtitle',
    notes: 'Trái nghĩa: 复杂 (phức tạp).',
    examples: [
      {
        sentence: '这个游戏的操作非常简单。',
        pinyin: 'Zhège yóuxì de cāozuò fēicháng jiǎndān.',
        translation: 'Cách điều khiển của game này rất đơn giản.',
      },
    ],
  },
  {
    word: '学习',
    language: 'zh',
    translation: 'học tập, học hỏi',
    pinyin: 'xuéxí',
    part_of_speech: 'Động từ (动词)',
    definition: 'Thu nhận kiến thức hoặc kỹ năng qua thực hành hoặc giảng dạy.',
    difficulty: 1,
    hsk_level: 1,
    source: 'default',
    notes: 'Có thể đi kèm tân ngữ: 学习汉语 (Học tiếng Hán).',
    examples: [
      {
        sentence: '我们每天都在学习新的知识。',
        pinyin: 'Wǒmen měitiān dōu zài xuéxí xīn de zhīshi.',
        translation: 'Chúng tôi mỗi ngày đều đang học kiến thức mới.',
      },
    ],
  },
  {
    word: '准备',
    language: 'zh',
    translation: 'chuẩn bị, dự định',
    pinyin: 'zhǔnbèi',
    part_of_speech: 'Động từ (动词)',
    definition: 'Làm sẵn việc cần thiết trước khi bắt đầu hành động.',
    difficulty: 2,
    hsk_level: 2,
    source: 'dictionary',
    notes: 'Cấu trúc: 准备 + Động từ / Danh từ.',
    examples: [
      {
        sentence: '你准备好明天的考试了吗？',
        pinyin: 'Nǐ zhǔnbèi hǎo míngtiān de kǎoshì le ma?',
        translation: 'Bạn đã chuẩn bị tốt cho kỳ thi ngày mai chưa?',
      },
    ],
  },
  {
    word: '流利',
    language: 'zh',
    translation: 'lưu loát, trôi chảy',
    pinyin: 'liúlì',
    part_of_speech: 'Tính từ (形容词)',
    definition: 'Nói năng hoặc viết lách mạch lạc, không ngắc ngứ.',
    difficulty: 2,
    hsk_level: 4,
    source: 'ai_tutor',
    notes: 'Thường dùng: 说得一流利 (nói rất lưu loát).',
    examples: [
      {
        sentence: '她能说一口流利的汉语。',
        pinyin: 'Tā néng shuō yī kǒu liúlì de Hànyǔ.',
        translation: 'Cô ấy có thể nói một giọng tiếng Hán lưu loát.',
      },
    ],
  },

  // English Vocabulary
  {
    word: 'beginner',
    language: 'en',
    translation: 'người mới bắt đầu, người tập sự',
    ipa: '/bɪˈɡɪn.ər/',
    part_of_speech: 'Noun',
    definition: 'A person just starting to learn a skill or take part in an activity.',
    difficulty: 1,
    cefr_level: 'A1',
    source: 'screen_ocr',
    notes: 'Synonyms: novice, newcomer. Antonym: expert.',
    examples: [
      {
        sentence: 'This guide is designed especially for beginners.',
        translation: 'Hướng dẫn này được thiết kế đặc biệt cho người mới bắt đầu.',
      },
    ],
  },
  {
    word: 'suitable',
    language: 'en',
    translation: 'thích hợp, phù hợp',
    ipa: '/ˈsuː.tə.bəl/',
    part_of_speech: 'Adjective',
    definition: 'Acceptable or right for someone or something.',
    difficulty: 2,
    cefr_level: 'B1',
    source: 'dictionary',
    notes: 'Collocation: suitable for someone / something.',
    examples: [
      {
        sentence: 'This movie is suitable for all ages.',
        translation: 'Bộ phim này phù hợp cho mọi lứa tuổi.',
      },
    ],
  },
  {
    word: 'proficiency',
    language: 'en',
    translation: 'sự thành thạo, năng lực giỏi',
    ipa: '/prəˈfɪʃ.ən.si/',
    part_of_speech: 'Noun',
    definition: 'A high degree of competence or skill; expertise.',
    difficulty: 3,
    cefr_level: 'B2',
    source: 'ai_tutor',
    notes: 'Collocation: language proficiency, demonstrate proficiency.',
    examples: [
      {
        sentence: 'She attained full proficiency in Chinese within two years.',
        translation: 'Cô ấy đạt được sự thành thạo hoàn toàn tiếng Trung trong vòng hai năm.',
      },
    ],
  },
  {
    word: 'pronunciation',
    language: 'en',
    translation: 'sự phát âm, cách phát âm',
    ipa: '/prəˌnʌn.siˈeɪ.ʃən/',
    part_of_speech: 'Noun',
    definition: 'The way in which a word or language is spoken.',
    difficulty: 2,
    cefr_level: 'A2',
    source: 'voice',
    notes: 'Notice the spelling: pro-NUN-ciation, not pronounce-iation.',
    examples: [
      {
        sentence: 'Pay special attention to your tones and pronunciation.',
        translation: 'Hãy đặc biệt chú ý đến thanh điệu và cách phát âm của bạn.',
      },
    ],
  },
  // Japanese Vocabulary
  {
    word: 'こんにちは',
    language: 'ja',
    translation: 'Xin chào',
    pinyin: 'konnichiwa',
    ipa: '/koɲɲitɕiwa/',
    part_of_speech: 'Lời chào',
    definition: 'Lời chào ban ngày thông dụng trong tiếng Nhật.',
    difficulty: 1,
    source: 'manual',
    notes: 'Dùng từ trưa đến chiều.',
    examples: [
      {
        sentence: '皆さん、こんにちは！',
        pinyin: 'Minasan, konnichiwa!',
        translation: 'Chào mọi người!',
      },
    ],
  },
  // Korean Vocabulary
  {
    word: '안녕하세요',
    language: 'ko',
    translation: 'Xin chào',
    pinyin: 'annyeonghaseyo',
    ipa: '/annjʌŋhasejo/',
    part_of_speech: 'Lời chào lịch sự',
    definition: 'Lời chào lịch thiệp, tôn kính trong tiếng Hàn.',
    difficulty: 1,
    source: 'manual',
    notes: 'Hình thức kính ngữ tiêu chuẩn.',
    examples: [
      {
        sentence: '안녕하세요, 만나서 반갑습니다.',
        pinyin: 'Annyeonghaseyo, mannaseo bangapseumnida.',
        translation: 'Xin chào, rất vui được gặp bạn.',
      },
    ],
  },
  // French Vocabulary
  {
    word: 'bonjour',
    language: 'fr',
    translation: 'Xin chào, chúc một ngày tốt lành',
    ipa: '/bɔ̃.ʒuʁ/',
    part_of_speech: 'Lời chào',
    definition: 'Lời chào ban ngày trang nhã, thông dụng.',
    difficulty: 1,
    cefr_level: 'A1',
    source: 'manual',
    notes: 'Dùng từ sáng đến trước lúc hoàng hôn.',
    examples: [
      {
        sentence: 'Bonjour tout le monde !',
        translation: 'Xin chào tất cả mọi người!',
      },
    ],
  },
];
